apiVersion: kustomize.config.k8s.io/v1beta1
namespace: application
images:
  - name: impl
    newName: nexus-dev.softwaregroup.com:5001/ut/impl-application
    newTag: latest
bases:
  - system/kustomize
resources:
  - docker.yaml
secretGenerator:
  - files:
      - rc.yaml=.ut_application_uatrc
    name: rc
    behavior: create
    type: Opaque
