run:
  hotReload: false
utBus:
  serviceBus:
    jsonrpc:
      domain: false
      metrics: true
      port: 8090
utLog:
  streams:
    fluentbit:
      level: trace
      stream: ../fluentdStream
      streamConfig:
        host: fluent-bit.logging.svc.cluster.local
        port: 24224
      type: raw
    udp:
      streamConfig:
        host: utportconsole-udp-log
