apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - files:
      - config=config.yaml
    literals:
      - "rc=install: /etc/ut_application_uat/rc"
    name: config
    type: Opaque
