apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - namespaces
  - deployments
  - secrets
  - services
  - ingresses
  - rbac
  - jobs
commonLabels:
  app.kubernetes.io/managed-by: ut-run
  app.kubernetes.io/part-of: application
kind: Kustomization
namespace: application
