module.exports = (...params) => [
    {main: require.resolve('ut-cache'), pkg: require.resolve('ut-cache/package.json')},
    {main: require.resolve('ut-telemetry'), pkg: require.resolve('ut-telemetry/package.json')},
    {main: require.resolve('../impl/server'), pkg: require.resolve('../package.json')},
    {main: require.resolve('ut-browser'), pkg: require.resolve('ut-browser/package.json')},
    {main: require.resolve('ut-db'), pkg: require.resolve('ut-db/package.json')},
    params[0].config.utCore && {main: require.resolve('ut-core'), pkg: require.resolve('ut-core/package.json')},
    params[0].config.utDocument && {main: require.resolve('ut-document'), pkg: require.resolve('ut-document/package.json')},
    params[0].config.utCustomer && {main: require.resolve('ut-customer'), pkg: require.resolve('ut-customer/package.json')},
    params[0].config.utNotice && {main: require.resolve('ut-notice'), pkg: require.resolve('ut-notice/package.json')},
    params[0].config.utUser && {main: require.resolve('ut-user'), pkg: require.resolve('ut-user/package.json')},
    params[0].config.utLedger && {main: require.resolve('ut-ledger'), pkg: require.resolve('ut-ledger/package.json')},
    params[0].config.utTransfer && {main: require.resolve('ut-transfer'), pkg: require.resolve('ut-transfer/package.json')},
    params[0].config.utBulk && {main: require.resolve('ut-bulk-payment'), pkg: require.resolve('ut-bulk-payment/package.json')},
    params[0].config.utUssd && {main: require.resolve('ut-ussd'), pkg: require.resolve('ut-ussd/package.json')},
    params[0].config.utRule && {main: require.resolve('ut-rule'), pkg: require.resolve('ut-rule/package.json')},
    params[0].config.utAgent && {main: require.resolve('ut-agent'), pkg: require.resolve('ut-agent/package.json')},
    params[0].config.utAml && {main: require.resolve('ut-aml'), pkg: require.resolve('ut-aml/package.json')},
    params[0].config.utReport && {main: require.resolve('ut-report'), pkg: require.resolve('ut-report/package.json')},
    params[0].config.utFulfill && {main: require.resolve('ut-fulfill'), pkg: require.resolve('ut-fulfill/package.json')},
    params[0].config.utEmail && {main: require.resolve('ut-email'), pkg: require.resolve('ut-email/package.json')},
    // bot
    params[0].config.utBot && {main: require.resolve('ut-bot'), pkg: require.resolve('ut-bot/package.json')},
    params[0].config.utSkype && {main: require.resolve('ut-skype'), pkg: require.resolve('ut-skype/package.json')},
    params[0].config.utMessenger && {main: require.resolve('ut-messenger'), pkg: require.resolve('ut-messenger/package.json')},
    params[0].config.utViber && {main: require.resolve('ut-viber'), pkg: require.resolve('ut-viber/package.json')},
    params[0].config.utSlack && {main: require.resolve('ut-slack'), pkg: require.resolve('ut-slack/package.json')},
    params[0].config.utSpeech && {main: require.resolve('ut-speech'), pkg: require.resolve('ut-speech/package.json')},
    params[0].config.utDialogflow && {main: require.resolve('ut-dialogflow'), pkg: require.resolve('ut-dialogflow/package.json')},
    params[0].config.utSmtpSim && {main: require.resolve('ut-smtp-sim'), pkg: require.resolve('ut-smtp-sim/package.json')},
    params[0].config.utBotSim && {main: require.resolve('ut-bot-sim'), pkg: require.resolve('ut-bot-sim/package.json')},
    // cms
    params[0].config.utAtm && {main: require.resolve('ut-atm'), pkg: require.resolve('ut-atm/package.json')},
    params[0].config.utCard && {main: require.resolve('ut-card'), pkg: require.resolve('ut-card/package.json')},
    params[0].config.utIso && {main: require.resolve('ut-iso'), pkg: require.resolve('ut-iso/package.json')},
    params[0].config.utPos && {main: require.resolve('ut-pos'), pkg: require.resolve('ut-pos/package.json')},
    // ctp
    params[0].config.utCtpPayshield && {main: require.resolve('ut-ctp-payshield'), pkg: require.resolve('ut-ctp-payshield/package.json')},
    params[0].config.utCtpPan && {main: require.resolve('ut-ctp-pan'), pkg: require.resolve('ut-ctp-pan/package.json')},
    params[0].config.utCtpAptra && {main: require.resolve('ut-ctp-aptra'), pkg: require.resolve('ut-ctp-aptra/package.json')},
    params[0].config.utCtpIso && {main: require.resolve('ut-ctp-iso'), pkg: require.resolve('ut-ctp-iso/package.json')},
    params[0].config.utCtpPos && {main: require.resolve('ut-ctp-pos'), pkg: require.resolve('ut-ctp-pos/package.json')},
    params[0].config.utIsoAcquirerSimulator && {main: require.resolve('ut-iso-acquirer-simulator'), pkg: require.resolve('ut-iso-acquirer-simulator/package.json')},
    params[0].config.utAtmSimulator && {main: require.resolve('ut-atm-simulator'), pkg: require.resolve('ut-atm-simulator/package.json')},
    // wallet
    params[0].config.utWallet && {main: require.resolve('ut-wallet'), pkg: require.resolve('ut-wallet/package.json')},
    // common
    params[0].config.utLogin && {main: require.resolve('ut-login'), pkg: require.resolve('ut-login/package.json')},
    params[0].config.utMirrors && {main: require.resolve('ut-mirrors'), pkg: require.resolve('ut-mirrors/package.json')},
    params[0].config.utAudit && {main: require.resolve('ut-audit'), pkg: require.resolve('ut-audit/package.json')},
    params[0].config.utHistory && {main: require.resolve('ut-history'), pkg: require.resolve('ut-history/package.json')},
    params[0].config.utBeertag && {main: require.resolve('../ut-beertag'), pkg: require.resolve('../ut-beertag/package.json')},
    params[0].config.utPortal && {main: require.resolve('ut-portal'), pkg: require.resolve('ut-portal/package.json')}
].filter(Boolean).map(item => [item, ...params]);
