apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
    app.kubernetes.io/component: impl-application
    app.kubernetes.io/instance: portal_8.10.11
    app.kubernetes.io/name: portal
    app.kubernetes.io/version: 8.10.11
    ut.layer: adminPortal
  name: adminapi-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: portal
  type: ClusterIP
