apiVersion: v1
kind: Service
metadata:
  labels:
    app: misc
    app.kubernetes.io/component: ut-aml
    app.kubernetes.io/instance: misc_7.4.4
    app.kubernetes.io/name: misc
    app.kubernetes.io/version: 7.4.4
    ut.layer: utAml.orchestrator
  name: aml-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: misc
  type: ClusterIP
