apiVersion: v1
kind: Service
metadata:
  labels:
    app: bot
    app.kubernetes.io/component: ut-bot
    app.kubernetes.io/instance: bot_7.15.4
    app.kubernetes.io/name: bot
    app.kubernetes.io/version: 7.15.4
    ut.layer: utBot.orchestrator
  name: bot-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: bot
  type: ClusterIP
