apiVersion: v1
kind: Service
metadata:
  labels:
    app: cms
    app.kubernetes.io/component: ut-card
    app.kubernetes.io/instance: cms_10.6.12
    app.kubernetes.io/name: cms
    app.kubernetes.io/version: 10.6.12
    ut.layer: utCard.orchestrator
  name: card-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: cms
  type: ClusterIP
