apiVersion: v1
kind: Service
metadata:
  labels:
    app: login
    app.kubernetes.io/component: ut-login
    app.kubernetes.io/instance: login_7.19.2
    app.kubernetes.io/name: login
    app.kubernetes.io/version: 7.19.2
    ut.layer: utLogin.adapter
  name: login-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: login
  type: ClusterIP
