apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-messenger
    app.kubernetes.io/instance: chat_7.9.7
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.9.7
    ut.layer: utMessenger.adapter
  name: messenger-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
