apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-skype
    app.kubernetes.io/instance: chat_7.10.6
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.10.6
    ut.layer: utSkype.orchestrator
  name: skypein-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
