apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctp
    app.kubernetes.io/component: ut-ctp-pos
    app.kubernetes.io/instance: ctp_8.2.2
    app.kubernetes.io/name: ctp
    app.kubernetes.io/version: 8.2.2
    ut.layer: utCtpPos.adapter
  name: tcp-tcppos
spec:
  ports:
    - name: tcp-tcppos
      port: 16000
      protocol: TCP
      targetPort: tcp-tcppos
  selector:
    app.kubernetes.io/name: ctp
  type: ClusterIP
