apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctp
    app.kubernetes.io/component: ut-ctp-pos
    app.kubernetes.io/instance: ctp_8.2.2
    app.kubernetes.io/name: ctp
    app.kubernetes.io/version: 8.2.2
    ut.layer: utCtpPos.adapter
  name: tcp-updatepos
spec:
  ports:
    - name: tcp-updatepos
      port: 16001
      protocol: TCP
      targetPort: tcp-updatepos
  selector:
    app.kubernetes.io/name: ctp
  type: ClusterIP
