apiVersion: v1
kind: Service
metadata:
  labels:
    app: eft
    app.kubernetes.io/component: ut-transfer
    app.kubernetes.io/instance: eft_8.8.18
    app.kubernetes.io/name: eft
    app.kubernetes.io/version: 8.8.18
    ut.layer: utTransfer.eft
  name: transferflow-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: eft
  type: ClusterIP
