apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctp
    app.kubernetes.io/component: ut-ctp-payshield
    app.kubernetes.io/instance: ctp_8.2.3
    app.kubernetes.io/name: ctp
    app.kubernetes.io/version: 8.2.3
    ut.layer: utCtpPayshield.adapter
  name: utctppayshield-payshield-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: ctp
  type: ClusterIP
