apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctp
    app.kubernetes.io/component: ut-ctp-pan
    app.kubernetes.io/instance: ctp_9.1.4
    app.kubernetes.io/name: ctp
    app.kubernetes.io/version: 9.1.4
    ut.layer: utCtpPan.adapter
  name: utctppan-ftpport-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: ctp
  type: ClusterIP
