apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-dialogflow
    app.kubernetes.io/instance: chat_7.10.7
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.10.7
    ut.layer: utDialogflow.adapter
  name: utdialogflow-dialogflow-http-dialogflow
spec:
  ports:
    - name: http-dialogflow
      port: 8084
      protocol: TCP
      targetPort: http-dialogflow
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
