apiVersion: v1
kind: Service
metadata:
  labels:
    app: eft
    app.kubernetes.io/component: ut-iso
    app.kubernetes.io/instance: eft_6.5.0
    app.kubernetes.io/name: eft
    app.kubernetes.io/version: 6.5.0
    ut.layer: utIso.eft
  name: utiso-isotransfer-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: eft
  type: ClusterIP
