apiVersion: v1
kind: Service
metadata:
  labels:
    app: cms
    app.kubernetes.io/component: ut-iso
    app.kubernetes.io/instance: cms_6.5.0
    app.kubernetes.io/name: cms
    app.kubernetes.io/version: 6.5.0
    ut.layer: utIso.orchestrator
  name: utiso-isodispatch-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: cms
  type: ClusterIP
