apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-messenger
    app.kubernetes.io/instance: chat_7.9.7
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.9.7
    ut.layer: utMessenger.adapter
  name: utmessenger-messenger-http-messenger
spec:
  ports:
    - name: http-messenger
      port: 8082
      protocol: TCP
      targetPort: http-messenger
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
