apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-skype
    app.kubernetes.io/instance: chat_7.10.6
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.10.6
    ut.layer: utSkype.adapter
  name: utskype-skype-http-skype
spec:
  ports:
    - name: http-skype
      port: 8080
      protocol: TCP
      targetPort: http-skype
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
