apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-speech
    app.kubernetes.io/instance: chat_7.10.2
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.10.2
    ut.layer: utSpeech.adapter
  name: utspeech-listen-http-listen
spec:
  ports:
    - name: http-listen
      port: 8087
      protocol: TCP
      targetPort: http-listen
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
