apiVersion: v1
kind: Service
metadata:
  labels:
    app: transfer
    app.kubernetes.io/component: ut-transfer
    app.kubernetes.io/instance: transfer_8.8.18
    app.kubernetes.io/name: transfer
    app.kubernetes.io/version: 8.8.18
    ut.layer: utTransfer.orchestrator
  name: uttransfer-transferdispatch-service
spec:
  ports:
    - name: http-jsonrpc
      port: 8090
      protocol: TCP
      targetPort: http-jsonrpc
  selector:
    app.kubernetes.io/name: transfer
  type: ClusterIP
