apiVersion: v1
kind: Service
metadata:
  labels:
    app: chat
    app.kubernetes.io/component: ut-viber
    app.kubernetes.io/instance: chat_7.9.9
    app.kubernetes.io/name: chat
    app.kubernetes.io/version: 7.9.9
    ut.layer: utViber.adapter
  name: utviber-viber-http-viber
spec:
  ports:
    - name: http-viber
      port: 8081
      protocol: TCP
      targetPort: http-viber
  selector:
    app.kubernetes.io/name: chat
  type: ClusterIP
